-- Create Food Library and Recipe Library tables
create table if not exists food_library (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  food_category text,
  calories_per_100g numeric default 0,
  protein_per_100g numeric default 0,
  carbs_per_100g numeric default 0,
  fat_per_100g numeric default 0,
  fibre_per_100g numeric default 0,
  omega3_per_100g_mg numeric default 0,
  seed_oil boolean default false,
  raw_payload jsonb default '{}'::jsonb
);

create table if not exists recipes_library (
  id uuid primary key default gen_random_uuid(),
  title text not null unique,
  meal_type text,
  calories_per_serving numeric default 0,
  protein_per_serving_g numeric default 0,
  carbs_per_serving_g numeric default 0,
  fat_per_serving_g numeric default 0,
  recipe_source text,
  ingredients jsonb default '[]'::jsonb,
  raw_payload jsonb default '{}'::jsonb
);

create table if not exists user_nutrition_goals (
  id uuid primary key default gen_random_uuid(),
  updated_at date not null default current_date,
  weight_lbs numeric default 165,
  body_fat_pct numeric default 15,
  calorie_target numeric default 2400,
  protein_target_g numeric default 160,
  fibre_target_g numeric default 50,
  omega3_target_mg numeric default 2000,
  fasting_protocol text default '16:8',
  fasting_start_hour integer default 20,
  fasting_end_hour integer default 12
);

create table if not exists weekly_meal_plans (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  created_at timestamp default now(),
  daily_plans jsonb default '{}'::jsonb,
  shopping_list jsonb default '[]'::jsonb,
  notes text
);

insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Almonds (1 oz, Generic)', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Almonds (¼ cup)', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Avocado Oil', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Avocado', 'fat', 160, 2.0, 8.5, 14.7, 6.7, 110, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Banana', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Black Beans', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Blueberries', 'fruit', 57, 0.7, 14.5, 0.3, 2.4, 58, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Broccoli', 'produce', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Chia Seeds', 'seed', 486, 16.5, 42.1, 30.7, 34.4, 17830, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Chicken Breast', 'protein', 165, 31.0, 0, 3.6, 0, 60, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Chickpeas', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Costco Bread', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Cottage Cheese', 'protein', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Eggs', 'protein', 143, 12.6, 0.7, 9.5, 0, 180, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Flaxseeds (Ground)', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Greek Yogurt', 'fermented-protein', 97, 9.0, 3.6, 5.0, 0, 50, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Hazelnuts', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Hemp Hearts', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Kefir 3.25%', 'dairy', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Kimchi', 'produce', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Kirkland Three Berry Blend', 'fruit', 52, 1.1, 12.0, 0.5, 3.5, 90, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Lean Fit Whey Protein Vanilla Bean', 'protein', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Lentils', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Liquid I.V. Electrolytes White Peach', 'supplement', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Milk 3.25%', 'dairy', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Mixed Nuts', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Normandy Mix', 'produce', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Oats', 'carb', 379, 13.2, 67.7, 6.9, 10.6, 110, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Olive Oil', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Organika Enhanced Collagen Protein', 'supplement', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Peanut Butter', 'fat', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Pumpkin', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Quinoa (Cooked)', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Quinoa (Raw)', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Salmon', 'protein', 206, 20.4, 0, 13.4, 0, 1800, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Sauerkraut (Wildbrine)', 'produce', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Spinach', 'vegetable', 23, 2.9, 3.6, 0.4, 2.2, 138, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Squirly Bread', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Stir Fry Mix', 'produce', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Sweet Potato', 'carb', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Vega Protein + Greens Creamy Vanilla', 'protein', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Vega Protein + Supergreens (Vanilla)', 'protein', 0, 0, 0, 0, 0, 0, false) on conflict (name) do nothing;
insert into food_library (name, food_category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, omega3_per_100g_mg, seed_oil) values ('Walnuts', 'nut', 654, 15.2, 13.7, 65.2, 6.7, 9080, false) on conflict (name) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('140', 'snack', 108, 6, 17, 2, 'Jalal''s Cookbook, p. 140') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('5 Ingredients Cookies', 'snack', 85, 5, 14, 2, 'Jalal''s Cookbook, p. 147') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Banana Bread Overnight Oats', 'breakfast', 383, 32, 39, 11, 'Jalal''s Cookbook, p. 124') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Bangin’ Protein Smoothie', 'shake', 500, 34, 55, 11, 'Jalal''s Cookbook, p. 137') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('BBQ Chicken Pizza', 'dinner', 418, 56, 31, 9, 'Jalal''s Cookbook, p. 58') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('BBQ Chicken Tenders', 'dinner', 227, 32, 22, 1, 'Jalal''s Cookbook, p. 52') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Beefy Pasta', 'dinner', 550, 39, 50, 13, 'Jalal''s Cookbook, p. 85') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('BL T Sandwich', 'breakfast', 490, 34, 31, 25, 'Jalal''s Cookbook, p. 112') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Breakfast Eggs & Potato', 'breakfast', 430, 27, 36, 15, 'Jalal''s Cookbook, p. 128') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Breakfast Fried Rice', 'breakfast', 450, 38, 35, 16, 'Jalal''s Cookbook, p. 123') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Breakfast Pizza (p. 110)', 'breakfast', 376, 30, 28, 16, 'Jalal''s Cookbook, p. 110') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Breakfast Pizza (p. 120)', 'breakfast', 500, 36, 32, 22, 'Jalal''s Cookbook, p. 120') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Breakfast Scrambled Wrap', 'breakfast', 500, 25, 35, 18, 'Jalal''s Cookbook, p. 129') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Breakfast Wrap', 'breakfast', 446, 33, 28, 21, 'Jalal''s Cookbook, p. 109') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Buffalo Chicken Mac & Cheese', 'dinner', 532, 63, 51, 9, 'Jalal''s Cookbook, p. 37') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Burrito Bowl Meal Prep', 'dinner', 508, 53, 56, 8, 'Jalal''s Cookbook, p. 19') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Butter Chicken Pasta Meal Prep', 'dinner', 422, 41, 43, 10, 'Jalal''s Cookbook, p. 17') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Cheesecake French Toast', 'breakfast', 446, 35, 45, 14, 'Jalal''s Cookbook, p. 107') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Cheesecake Overnight Oats', 'breakfast', 395, 43, 42, 8, 'Jalal''s Cookbook, p. 121') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Cheesy Beef Bolognese Tacos', 'dinner', 249, 24, 21, 8, 'Jalal''s Cookbook, p. 78') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Cheesy Chicken Pizza-Dilla', 'dinner', 594, 56, 40, 22, 'Jalal''s Cookbook, p. 30') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Cheesy Chicken Quesadilla', 'dinner', 487, 53, 26, 19, 'Jalal''s Cookbook, p. 48') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chewy Cookies', 'snack', 104, 7, 5, 5, 'Jalal''s Cookbook, p. 142') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chicken Chow Mein Noodles', 'dinner', 455, 43, 48, 9, 'Jalal''s Cookbook, p. 10') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chicken Fajita Bowl', 'dinner', 485, 55, 46, 9, 'Jalal''s Cookbook, p. 41') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chicken Fajita Rice', 'dinner', 408, 39, 41, 9, 'Jalal''s Cookbook, p. 8') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chicken Fajita Wraps', 'dinner', 384, 40, 24, 14, 'Jalal''s Cookbook, p. 21') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chicken Kebabs with Y ellow Rice', 'dinner', 427, 54, 46, 7, 'Jalal''s Cookbook, p. 67') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chinese Beef Stir Fry', 'dinner', 487, 49, 39, 13.5, 'Jalal''s Cookbook, p. 80') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Chow Mein Noodles', 'dinner', 461, 55, 44, 7, 'Jalal''s Cookbook, p. 53') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Cream Stuffed French Toast', 'breakfast', 570, 48, 42, 15, 'Jalal''s Cookbook, p. 113') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Butter Chicken & Garlic Naan', 'dinner', 574, 67, 48.5, 12.5, 'Jalal''s Cookbook, p. 34') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Chicken Mac and Cheese', 'dinner', 498, 52, 49, 11.5, 'Jalal''s Cookbook, p. 14') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Chicken Pasta', 'dinner', 488, 60, 48, 6, 'Jalal''s Cookbook, p. 42') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Mozzarella Pasta Meal Prep', 'dinner', 401, 42, 37, 9, 'Jalal''s Cookbook, p. 26') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Rasta Pasta', 'dinner', 551, 50, 51, 14, 'Jalal''s Cookbook, p. 65') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Salmon Pasta', 'dinner', 640, 57, 42, 25, 'Jalal''s Cookbook, p. 96') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Scrambled Eggs on Toast', 'breakfast', 425, 35, 36, 12, 'Jalal''s Cookbook, p. 115') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Creamy Tuscan Chicken Pasta', 'dinner', 572, 67, 52, 11, 'Jalal''s Cookbook, p. 44') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy & Sticky Orange Chicken', 'dinner', 455, 48, 57, 6, 'Jalal''s Cookbook, p. 12') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy Chicken Burgers', 'dinner', 441, 42, 39, 13, 'Jalal''s Cookbook, p. 36') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy Chicken Fried Rice', 'dinner', 529, 61, 46, 12, 'Jalal''s Cookbook, p. 45') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy Chicken Wraps', 'dinner', 415, 42, 46, 7, 'Jalal''s Cookbook, p. 23') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy Orange Chicken Sandwich', 'dinner', 511, 41, 56, 12, 'Jalal''s Cookbook, p. 15') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy Potatoes & Scrambled Eggs', 'breakfast', 451, 27, 43, 19, 'Jalal''s Cookbook, p. 106') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Crispy Salmon Fried Rice', 'dinner', 531, 45, 44, 19, 'Jalal''s Cookbook, p. 91') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Delicious Chicken Stir Fry', 'dinner', 418, 56, 38, 7, 'Jalal''s Cookbook, p. 59') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Delicious Shawarma Bowl', 'dinner', 479, 56, 43, 9, 'Jalal''s Cookbook, p. 55') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Delicious Tomato Chicken', 'dinner', 390, 43.5, 39.5, 6, 'Jalal''s Cookbook, p. 61') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Double Smash Burger', 'dinner', 550, 52, 30, 20, 'Jalal''s Cookbook, p. 88') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Eggs on Toast MY W A Y', 'breakfast', 450, 24, 32, 24, 'Jalal''s Cookbook, p. 125') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Fluffy Pancakes', 'snack', 385, 53, 19, 11, 'Jalal''s Cookbook, p. 144') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Fluffy Thicc Pancakes', 'breakfast', 431, 34, 46, 10, 'Jalal''s Cookbook, p. 117') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('French Toast Muffins', 'breakfast', 103, 10, 12, 1, 'Jalal''s Cookbook, p. 127') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Fresh Salmon Bowl', 'dinner', 800, 60, 67, 24, 'Jalal''s Cookbook, p. 99') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Fried Rice Burritos', 'dinner', 470, 43, 34, 18, 'Jalal''s Cookbook, p. 28') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Fudgy Brownie Bowl', 'snack', 192, 19, 25, 3, 'Jalal''s Cookbook, p. 146') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Garlic Parmesan Fries', 'dinner', 356, 53, 14, 9, 'Jalal''s Cookbook, p. 102') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Golden Smoothie Bowl', 'snack', 500, 37, 45, 15, 'Jalal''s Cookbook, p. 145') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Golden Y ellow Rice', 'dinner', 213, 6, 44, 2, 'Jalal''s Cookbook, p. 104') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Halal Cart Chicken & Rice', 'dinner', 430, 41, 42, 11, 'Jalal''s Cookbook, p. 18') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Healthy Chicken Tikka Masala', 'dinner', 491, 58, 48, 8, 'Jalal''s Cookbook, p. 50') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Healthy Pad Thai (p. 46)', 'dinner', 558, 62, 50, 12, 'Jalal''s Cookbook, p. 46') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Healthy Pad Thai (p. 62)', 'dinner', 538, 58, 54, 13, 'Jalal''s Cookbook, p. 62') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Healthy Spaghetti Bolognese', 'dinner', 526, 51, 49, 16, 'Jalal''s Cookbook, p. 83') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Healthy Thai Green Curry', 'dinner', 546, 52, 48, 16, 'Jalal''s Cookbook, p. 63') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Alfredo Pasta', 'dinner', 542, 65, 47, 12, 'Jalal''s Cookbook, p. 13') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Butter Chicken', 'dinner', 475, 58, 48, 5, 'Jalal''s Cookbook, p. 47') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Cheesy Chicken Tacos', 'dinner', 230, 25, 18, 6, 'Jalal''s Cookbook, p. 20') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Creamy Beef Pasta', 'dinner', 478, 48, 50, 10, 'Jalal''s Cookbook, p. 81') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Creamy Chicken', 'dinner', 507, 62.5, 48.5, 7, 'Jalal''s Cookbook, p. 11') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Egg Sandwich', 'breakfast', 324, 26, 31, 7.5, 'Jalal''s Cookbook, p. 108') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Fried Rice', 'dinner', 519, 58, 46, 11.5, 'Jalal''s Cookbook, p. 54') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Kebab', 'dinner', 405, 39, 36, 10, 'Jalal''s Cookbook, p. 89') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Lasagna', 'dinner', 465, 58, 33, 12, 'Jalal''s Cookbook, p. 82') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Mac & Cheese Burritos', 'dinner', 427, 43, 45, 9, 'Jalal''s Cookbook, p. 32') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Peri Peri Chicken Pasta', 'dinner', 463, 47, 46, 10, 'Jalal''s Cookbook, p. 7') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Pesto Pasta', 'dinner', 548, 62, 45, 13, 'Jalal''s Cookbook, p. 35') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Pizza Bites', 'dinner', 93, 10, 7.5, 2, 'Jalal''s Cookbook, p. 77') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Quesadilla', 'breakfast', 450, 39, 32, 16, 'Jalal''s Cookbook, p. 118') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('High Protein Shawarma', 'dinner', 390, 45, 35, 7, 'Jalal''s Cookbook, p. 57') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey BBQ Chicken Mac & Cheese', 'dinner', 511, 50, 50, 10, 'Jalal''s Cookbook, p. 6') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey Chicken & Rice', 'dinner', 510, 52, 60, 6, 'Jalal''s Cookbook, p. 73') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey Garlic Chicken Noodles', 'dinner', 477, 47, 48, 11, 'Jalal''s Cookbook, p. 16') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey Garlic Chicken', 'dinner', 434, 50, 49, 4, 'Jalal''s Cookbook, p. 38') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey Lemon Chicken Meal Prep', 'dinner', 415, 40, 44, 8, 'Jalal''s Cookbook, p. 27') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey Salmon & Rice', 'dinner', 615, 57, 46, 20, 'Jalal''s Cookbook, p. 97') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Honey Sriracha Crispy Tenders', 'dinner', 335, 40, 37, 2, 'Jalal''s Cookbook, p. 64') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('In N Out Double Double Cheeseburgers', 'dinner', 502, 60, 34, 14, 'Jalal''s Cookbook, p. 79') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Juicy & Tender Whole Chicken', 'dinner', 525, 77, 9, 17, 'Jalal''s Cookbook, p. 72') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Juicy Chicken Burger', 'dinner', 493, 42, 32, 19, 'Jalal''s Cookbook, p. 70') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('KFC Zinger Rice Box', 'dinner', 506, 56, 57, 7, 'Jalal''s Cookbook, p. 43') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Korean Fried Chicken Burgers', 'dinner', 569, 47, 66, 13, 'Jalal''s Cookbook, p. 9') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Lean Stuffed Peppers', 'dinner', 210, 30, 8, 6, 'Jalal''s Cookbook, p. 75') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Lemon Garlic Kebabs', 'dinner', 478, 53, 48, 8, 'Jalal''s Cookbook, p. 24') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Lemon Pepper Chicken Wraps', 'dinner', 409, 41, 32, 13, 'Jalal''s Cookbook, p. 22') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Loaded Breakfast Eggs', 'breakfast', 600, 42, 34, 24, 'Jalal''s Cookbook, p. 114') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Loaded Fries!', 'dinner', 520, 49, 42, 15, 'Jalal''s Cookbook, p. 90') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Loaded Nachos', 'dinner', 347, 36, 25, 15, 'Jalal''s Cookbook, p. 71') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Loaded Omelette (Low carb)', 'breakfast', 380, 46, 5, 14, 'Jalal''s Cookbook, p. 119') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Loaded Sandwich', 'breakfast', 500, 40, 32, 17, 'Jalal''s Cookbook, p. 130') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Low Calorie Burrito Bowl', 'dinner', 519, 57, 57, 7, 'Jalal''s Cookbook, p. 56') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Low Calorie Chicken Biryani', 'dinner', 476, 55, 44, 9, 'Jalal''s Cookbook, p. 49') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Low Calorie Crispy Fries', 'dinner', 351, 61, 11, 7, 'Jalal''s Cookbook, p. 103') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Mango Habanero Chicken', 'dinner', 442, 50, 50, 6, 'Jalal''s Cookbook, p. 33') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Mexican One-Pan Chicken', 'dinner', 482.5, 55.5, 55, 4, 'Jalal''s Cookbook, p. 60') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Mongolian Beef', 'dinner', 573, 65, 48, 11, 'Jalal''s Cookbook, p. 86') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('One Pot Chicken & Rice', 'dinner', 531, 58, 44, 11, 'Jalal''s Cookbook, p. 76') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('One-Pan Tomato Beef Pasta', 'dinner', 480, 40, 48, 12, 'Jalal''s Cookbook, p. 84') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('One-Pot Chicken Parm', 'dinner', 531, 58, 44, 11, 'Jalal''s Cookbook, p. 69') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Original Overnight Oats', 'breakfast', 400, 38, 48, 6, 'Jalal''s Cookbook, p. 122') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Pancake Tacos', 'breakfast', 186, 18, 13, 6, 'Jalal''s Cookbook, p. 111') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Peri Peri Burgers', 'dinner', 441, 43, 29, 17, 'Jalal''s Cookbook, p. 29') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Peri Peri Chicken & Spicy Rice', 'dinner', 452, 38, 43, 14, 'Jalal''s Cookbook, p. 25') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Post-Workout Shake', 'shake', 0, 0, 0, 0, '0') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Power Burrito', 'dinner', 520, 43, 46, 20, 'Jalal''s Cookbook, p. 68') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Protein Ice Cream', 'snack', 450, 40, 45, 11, 'Jalal''s Cookbook, p. 141') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Protein Rice Krispies Bars', 'snack', 113, 7, 13, 4, 'Jalal''s Cookbook, p. 143') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Rice Pancakes', 'snack', 500, 45, 40, 11, 'Jalal''s Cookbook, p. 148') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Salmon Power Bowl', 'dinner', 594, 42, 48, 26, 'Jalal''s Cookbook, p. 93') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Sesame Chicken', 'dinner', 460, 53, 45, 5, 'Jalal''s Cookbook, p. 66') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Snickers Shake', 'shake', 500, 33, 55, 20, 'Jalal''s Cookbook, p. 139') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Spicy Chicken Wraps', 'dinner', 347, 38, 24, 11, 'Jalal''s Cookbook, p. 5') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Spicy Creamy Breakfast Wraps', 'breakfast', 311, 26, 22, 13, 'Jalal''s Cookbook, p. 105') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Steak Stir Fry', 'dinner', 290, 39, 17, 9, 'Jalal''s Cookbook, p. 87') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Sweet and Sour Chicken', 'dinner', 434, 50, 49, 4, 'Jalal''s Cookbook, p. 51') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Sweet n Sour Chicken Fried Rice', 'dinner', 457, 53, 49, 6, 'Jalal''s Cookbook, p. 31') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Sweet Potato Pancakes', 'breakfast', 520, 60, 50, 8, 'Jalal''s Cookbook, p. 131') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Thin Crust Pizza', 'dinner', 570, 60, 45, 10, 'Jalal''s Cookbook, p. 74') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Tiramisu Pancakes', 'breakfast', 459, 43, 55, 7, 'Jalal''s Cookbook, p. 116') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Tuna Pasta Bake', 'dinner', 340, 40, 30, 6, 'Jalal''s Cookbook, p. 100') on conflict (title) do nothing;
insert into recipes_library (title, meal_type, calories_per_serving, protein_per_serving_g, carbs_per_serving_g, fat_per_serving_g, recipe_source) values ('Tuna Stir Fry', 'dinner', 325, 34, 35, 6, 'Jalal''s Cookbook, p. 98') on conflict (title) do nothing;